---
- name: Deploy Scientific Calculator Container
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: "5unnysunny/scalculator:{{ image_tag }}" 
        source: pull

    - name: Run container
      community.docker.docker_container:
        name: scientific-calculator
        image: "5unnysunny/scalculator:{{ image_tag }}"
        state: started
        interactive: true
        tty: true
        command: python scalculator.py